site_name: AMERICANICHE ACADEMY
dev_addr: 0.0.0.0:8000
nav:
  - Home: index.md
  - About: about.md
  - Generation Of Keys: gen.md
  - Deployment: deployment.md
  - Result: result.md
theme: readthedocs  